#!/bin/bash
#Check if Apache, PHP have been installed, if not, execute apacheinstall
./apacheinstall

#Check if mysql has been already installed
mysqlcheck=$(dpkg-query -W -f='${Status}' mysql | grep -c 'ok installed')

if [ "$mysqlcheck" = "1" ]; then
	echo "mysql has already been installed on this system"
else
	echo "Installing mysql"
	apt-get install mysql-server --assume-yes
	mysql --version
fi
