#!/bin/bash
#add user, no password, add home directotory
filename=$1
for rida in `cat $filename`
do
	name=`echo $rida | cut -f1 -d:`
	sudo useradd -m $name
	echo "$rida" | chpasswd
	echo "User $name’s password changed!"
done
