#!/bin/bash
#add user, no password, add home directotory
filename=$1
for name in `cat $filename | cut -f1 -d:`
do
	useradd -m $name

for pass in `cat $filename`
do
	echo "$pass" | chpasswd

done
done
